---
name: cf-redis
director_uuid: 9bca5701-66c0-43ee-a4d0-64813b4b5ece
releases:
- name: cf-redis
  version: latest
compilation:
  cloud_properties:
    name: random
  network: services
  reuse_compilation_vms: true
  workers: 2
update:
  canaries: 1
  canary_watch_time: 30000-180000
  update_watch_time: 30000-180000
  max_in_flight: 4
networks:
- name: services
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.3.32/30
    reserved:
    - 10.244.3.33
  - cloud_properties:
      name: random
    range: 10.244.3.36/30
    reserved:
    - 10.244.3.37
  - cloud_properties:
      name: random
    range: 10.244.3.40/30
    reserved:
    - 10.244.3.41
  - cloud_properties:
      name: random
    range: 10.244.3.44/30
    reserved:
    - 10.244.3.45
    static:
    - 10.244.3.46
  - cloud_properties:
      name: random
    range: 10.244.3.48/30
    reserved:
    - 10.244.3.49
  - cloud_properties:
      name: random
    range: 10.244.3.52/30
    reserved:
    - 10.244.3.53
    static:
    - 10.244.3.54
  - cloud_properties:
      name: random
    range: 10.244.3.56/30
    reserved:
    - 10.244.3.57
    static:
    - 10.244.3.58
  - cloud_properties:
      name: random
    range: 10.244.3.60/30
    reserved:
    - 10.244.3.61
    static:
    - 10.244.3.62
  - cloud_properties:
      name: random
    range: 10.244.3.64/30
    reserved:
    - 10.244.3.65
    static:
    - 10.244.3.66
  - cloud_properties:
      name: random
    range: 10.244.3.68/30
    reserved:
    - 10.244.3.69
    static:
    - 10.244.3.70
resource_pools:
- cloud_properties:
    ram: 1024
    name: random
  name: services-small
  network: services
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
jobs:
- name: dedicated-node
  templates:
  - name: dedicated-node
    release: cf-redis
  - name: syslog-configurator
    release: cf-redis
  instances: 1
  resource_pool: services-small
  persistent_disk: 4096
  networks:
  - name: services
    static_ips:
    - 10.244.3.54
- name: cf-redis-broker
  templates:
  - name: cf-redis-broker
    release: cf-redis
  - name: syslog-configurator
    release: cf-redis
  instances: 1
  resource_pool: services-small
  persistent_disk: 4096
  networks:
  - name: services
    static_ips:
    - 10.244.3.46
- name: broker-registrar
  instances: 1
  lifecycle: errand
  networks:
  - name: services
  resource_pool: services-small
  templates:
  - name: broker-registrar
    release: cf-redis
  properties:
    broker:
      name: redis
      host: redis-broker.bosh-lite.com
      username: admin
      password: admin
- name: broker-deregistrar
  instances: 1
  lifecycle: errand
  networks:
  - name: services
  resource_pool: services-small
  templates:
  - name: broker-deregistrar
    release: cf-redis
  properties:
    broker:
      name: redis
      host: redis-broker.bosh-lite.com
      username: admin
      password: admin
- name: smoke-tests
  instances: 1
  lifecycle: errand
  networks:
  - name: services
  resource_pool: services-small
  templates:
  - name: smoke-tests
    release: cf-redis
properties:
  syslog_aggregator:
    address: 127.0.0.1
    port: 1234
  cf:
    api_url: https://api.bosh-lite.com
    apps_domain: bosh-lite.com
    admin_username: admin
    admin_password: admin
    nats:
      host: 10.244.0.6
      port: 4222
      username: nats
      password: nats
  redis:
    host: redis-broker.bosh-lite.com
    maxmemory: 262144000
    config_command: config
    save_command: save
    bg_save_command: bgsave
    broker:
      backend_host: 10.244.3.46
      network: services
      dedicated_nodes:
      - 10.244.3.54
      service_instance_limit: 3
      auth:
        username: admin
        password: admin
      backups:
        path:
        access_key_id:
        secret_access_key:
        endpoint_url:
        bucket_name:
