meta:
  environment: YOUR_ENVIRONMENT_NAME
  external_domain: YOUR_CF_SYSTEM_DOMAIN
  apps_domain: YOUR_CF_APPS_DOMAIN
  nats:
    host: 10.0.16.11
    port: 4222
    username: NATS_USERNAME_FROM_CF_RELEASE
    password: NATS_PASSWORD_FROM_CF_RELEASE
  syslog_aggregator:
    address: 127.0.0.1
    port: 1234

director_uuid: YOUR_DIRECTOR_UUID

networks:
- name: redis_z1
  type: manual
  subnets:
  - range: 10.0.16.0/20
    gateway: 10.0.16.1
    reserved:
    - 10.0.16.2 - 10.0.16.254
    static:
    - 10.0.17.1 - 10.0.17.100
    dns:
    - 10.0.0.2
    cloud_properties:
      subnet: YOUR_SUBNET_ID
      security_group: YOUR_SECURITY_GROUP_NAME

properties:
  template_only:
    dedicated_plan:
      instance_count: 5 # NB, IF YOU INCREASE THIS TO MORE THAN 10 YOU MUST ALSO ADD IPS TO THE JOB
    shared_plan:
      instance_limit: 5 
      max_memory: 262144000
  redis:
    broker:
      enable_service_access: true
      service_name: redis
      backups: #Leave this section empty if you don't require backups.
        access_key_id: YOUR_S3_ACCESS_KEY_ID
        secret_access_key: YOUR_S3_SECRET_ACCESS_KEY 
        endpoint_url: S3_ENDPOINT_FOR_YOUR_REGION
        bucket_name: YOUR_S3_BUCKET
        path: YOUR_S3_BACKUP_PATH
  cf:
    admin_username: YOUR_CF_ADMIN_USERNAME
    api_url: https://api.YOUR_CF_SYSTEM_DOMAIN
    admin_password: YOUR_CF_ADMIN_PASSWORD


jobs:
- name: cf-redis-broker
  properties:
    broker:
      username: A_USERNAME_YOU_MAKE_UP
      password: A_PASSWORD_YOU_MAKE_UP
  
- name: dedicated-node
  instances: 1
  networks:
  - name: redis_z1
    static_ips:
    - 10.0.17.2 - 10.0.17.6


